env:
  DEFAULT_JDK_DIST: temurin
  DEFAULT_JDK_VERSION: 17
jobs:
  tests:
    name: Jakarta
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.DEFAULT_JDK_DIST }}
        java-version: ${{ env.DEFAULT_JDK_VERSION }}
    - continue-on-error: true
      name: Update maven settings
      run: mkdir -p ~/.m2 ; cp .github/maven-settings.xml ~/.m2/
    - continue-on-error: true
      name: Cache Maven repo
      uses: actions/cache@v2
      with:
        key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/keycloak

          '
        restore-keys: cache-1-${{ runner.os }}-m2
    - continue-on-error: true
      name: Get Keycloak
      run: .github/scripts/prepare-local-server.sh
    - continue-on-error: true
      name: Start Keycloak
      run: .github/scripts/start-local-server.sh
    - continue-on-error: true
      name: Run unit tests
      run: .github/scripts/run-tests.sh jakarta
  tests-extension:
    name: Extension
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.DEFAULT_JDK_DIST }}
        java-version: ${{ env.DEFAULT_JDK_VERSION }}
    - continue-on-error: true
      name: Update maven settings
      run: mkdir -p ~/.m2 ; cp .github/maven-settings.xml ~/.m2/
    - continue-on-error: true
      name: Cache Maven repo
      uses: actions/cache@v2
      with:
        key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/keycloak

          '
        restore-keys: cache-1-${{ runner.os }}-m2
    - continue-on-error: true
      name: Get Keycloak
      run: .github/scripts/prepare-local-server.sh
    - continue-on-error: true
      name: Start Keycloak
      run: .github/scripts/start-local-server.sh extension
    - continue-on-error: true
      name: Run unit tests
      run: .github/scripts/run-tests.sh extension
  tests-js:
    name: JavaScript
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.DEFAULT_JDK_DIST }}
        java-version: ${{ env.DEFAULT_JDK_VERSION }}
    - continue-on-error: true
      name: Get Keycloak
      run: .github/scripts/prepare-local-server.sh
    - continue-on-error: true
      name: Start Keycloak
      run: .github/scripts/start-local-server.sh
    - continue-on-error: true
      name: Run unit tests
      run: .github/scripts/run-tests.sh js
  tests-nodejs:
    name: Node.js
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.DEFAULT_JDK_DIST }}
        java-version: ${{ env.DEFAULT_JDK_VERSION }}
    - continue-on-error: true
      name: Get Keycloak
      run: .github/scripts/prepare-local-server.sh
    - continue-on-error: true
      name: Start Keycloak
      run: .github/scripts/start-local-server.sh
    - continue-on-error: true
      name: Run unit tests
      run: .github/scripts/run-tests.sh nodejs
  tests-spring:
    name: Spring
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.DEFAULT_JDK_DIST }}
        java-version: ${{ env.DEFAULT_JDK_VERSION }}
    - continue-on-error: true
      name: Update maven settings
      run: mkdir -p ~/.m2 ; cp .github/maven-settings.xml ~/.m2/
    - continue-on-error: true
      name: Cache Maven repo
      uses: actions/cache@v2
      with:
        key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/keycloak

          '
        restore-keys: cache-1-${{ runner.os }}-m2
    - continue-on-error: true
      name: Get Keycloak
      run: .github/scripts/prepare-local-server.sh
    - continue-on-error: true
      name: Start Keycloak
      run: .github/scripts/start-local-server.sh
    - continue-on-error: true
      name: Run unit tests
      run: .github/scripts/run-tests.sh spring
name: Keycloak Integration CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
