jobs:
  run-ci:
    name: Run CI workflow
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-quickstarts'
      run: gh workflow run -R keycloak/keycloak-quickstarts ci.yml -r main
name: Scheduled workflows
on:
  repository_dispatch:
    types: trigger-ga___schedule.yml
